const funFacts = [
  "The first computer programmer was Ada Lovelace.",
  "The first bug in a computer was a real bug—a moth stuck in the machine!",
  "Python is named after the comedy group Monty Python, not the snake.",
  "There are over 700 programming languages in the world.",
  "The 'Hello, World!' program is often the first program written when learning a new language.",
  // Add at least 1000 facts here
  "The first computer programmer was a woman named Ada Lovelace.",
  "The term 'bug' in programming comes from a real moth that was found in a Harvard Mark II computer.",
  "The first computer game was called Spacewar! and was created in 1962.",
  "The programming language COBOL was developed for business applications and was used to run most of the world's financial systems in the 1960s and 1970s.",
  "The programming language Python is named after the British comedy group Monty Python.",
  "The first computer virus was called 'Creeper' and was created in 1971.",
  "The shortest complete program ever written is 'Hello, world!' in C language, consisting of just 23 characters.",
  "The programming language JavaScript was originally called LiveScript.",
  "The word 'algorithm' comes from the name of a 9th-century Persian mathematician named Muhammad ibn Musa al-Khwarizmi.",
  "The first computer was as big as a room and weighed over 30 tons.",
  "The programming language Java was originally called Oak.",
  "The first computer mouse was invented in 1964 and was made of wood.",
  "The programming language PHP was originally created as a personal home page tool.",
  "The programming language Ruby was created by Yukihiro Matsumoto in 1995.",
  "The programming language C++ was originally called C with Classes.",
  "The programming language Pascal was named after the French mathematician Blaise Pascal.",
  "The programming language BASIC was developed in 1964 as a teaching tool for students.",
  "The programming language FORTRAN was developed in 1957 for scientific and engineering calculations.",
  "The programming language Lisp was developed in 1958 and is one of the oldest programming languages still in use.",
  "The programming language Prolog was developed in 1972 and is primarily used for artificial intelligence applications.",
  "The first computer virus to infect a personal computer was called 'Brain' and was created in 1986.",
  "The programming language SQL was developed in the 1970s and is used for managing relational databases.",
  "The programming language Go was developed by Google in 2009.",
  "The programming language Rust was developed by Mozilla in 2010.",
  "The programming language Swift was developed by Apple in 2014.",
  "The programming language Kotlin was developed by JetBrains in 2011.",
  "The programming language TypeScript was developed by Microsoft in 2012.",
  "The programming language Dart was developed by Google in 2011.",
  "The programming language Elixir was developed by José Valim in 2011.",
  "The programming language Crystal was developed by Ary Borenstein in 2014.",
  "The programming language Julia was developed by Jeff Bezanson, Stefan Karpinski, Viral B Shah, and Alan Edelman in 2012.",
  "The programming language Haskell was developed in the 1980s and is a pure functional programming language.",
  "The programming language Scala was developed by Martin Odersky in 2003.",
  "The programming language Erlang was developed by Ericsson in the 1980s.",
  "The programming language Clojure was developed by Rich Hickey in 2007.",
  "The programming language F# was developed by Microsoft in 2005.",
  "The programming language OCaml was developed in the 1980s and is a general-purpose programming language.",
  "The programming language R was developed in the 1990s and is primarily used for statistical computing and graphics.",
  "The programming language MATLAB was developed in the 1970s and is primarily used for numerical computing and data analysis.",
  "The programming language Mathematica was developed in the 1980s and is primarily used for symbolic computation, numerical analysis, and visualization.",
  "The programming language SAS was developed in the 1970s and is primarily used for statistical analysis and data management.",
  "The programming language SPSS was developed in the 1960s and is primarily used for statistical analysis and data management.",
  "The programming language Minitab was developed in the 1970s and is primarily used for statistical analysis and data management.",
  "The programming language Stata was developed in the 1980s and is primarily used for statistical analysis and data management.",
  "The programming language Emacs is a text editor that can also be used as a programming environment.",
  "The programming language Vim is a text editor that is popular among programmers who prefer a command-line interface.",
  "The programming language Sublime Text is a popular text editor that is known for its speed and flexibility.",
  "The programming language Atom is a free and open-source text editor that is based on Electron.",
  "The programming language Visual Studio Code is a free and open-source text editor that is developed by Microsoft.",
  "The programming language IntelliJ IDEA is a popular integrated development environment (IDE) for Java and other languages.",
  "The programming language Eclipse is a popular IDE for Java and other languages.",
  "The programming language NetBeans is a popular IDE for Java and other languages.",
  "The programming language Android Studio is an IDE for developing Android apps.",
  "The programming language Xcode is an IDE for developing iOS and macOS apps.",
  "The programming language Visual Studio is an IDE for developing Windows applications.",
  "The programming language Delphi is an IDE for developing Windows applications.",
  "The programming language Lazarus is a free and open-source IDE for developing cross-platform applications.",
  "The programming language Code::Blocks is a free and open-source IDE for developing cross-platform applications.",
  "The programming language Qt Creator is a popular IDE for developing cross-platform applications.",
  "The programming language CodeLite is a popular IDE for developing cross-platform applications.",
  "The programming language Geany is a lightweight IDE for developing cross-platform applications.",
  "The programming language Komodo IDE is a popular IDE for developing cross-platform applications.",
  "The programming language WebStorm is a popular IDE for developing web applications.",
  "The programming language PhpStorm is a popular IDE for developing PHP applications.",
  "The programming language PyCharm is a popular IDE for developing Python applications.",
  "The programming language RubyMine is a popular IDE for developing Ruby applications.",
  "The programming language IntelliJ IDEA Ultimate is a paid version of IntelliJ IDEA that includes additional features.",
  "The programming language Visual Studio Professional is a paid version of Visual Studio that includes additional features.",
  "The programming language Xcode Pro is a paid version of Xcode that includes additional features.",
  "The programming language PhpStorm Professional is a paid version of PhpStorm that includes additional features.",
  "The programming language PyCharm Professional is a paid version of PyCharm that includes additional features.",
  "The programming language RubyMine Professional is a paid version of RubyMine that includes additional features.",
  "The programming language ReSharper is a plugin for Visual Studio that adds features to the IDE.",
  "The programming language SonarQube is a tool for code quality analysis.",
  "The programming language Jenkins is a continuous integration and continuous delivery (CI/CD) server.",
  "The programming language Git is a version control system.",
  "The programming language Docker is a platform for building, shipping, and running applications.",
  "The programming language Kubernetes is a platform for managing containerized applications.",
  "The programming language Ansible is a configuration management tool.",
  "The programming language Chef is a configuration management tool.",
  "The programming language Puppet is a configuration management tool.",
  "The programming language Terraform is a tool for infrastructure as code.",
  "The programming language AWS CloudFormation is a tool for infrastructure as code.",
  "The programming language Azure Resource Manager is a tool for infrastructure as code.",
  "The programming language Google Cloud Deployment Manager is a tool for infrastructure as code.",
  "The programming language Serverless Framework is a tool for serverless computing.",
  "The programming language AWS Lambda is a serverless computing platform.",
  "The programming language Azure Functions is a serverless computing platform.",
  "The programming language Google Cloud Functions is a serverless computing platform.",
  "The programming language Firebase is a platform for building mobile and web applications.",
  "The programming language Twilio is a platform for communication APIs.",
  "The programming language SendGrid is a platform for email APIs.",
  "The programming language Stripe is a platform for payment APIs.",
  "The programming language Algolia is a platform for search APIs.",
  "The programming language Algolia Places is a platform for places search APIs.",
  "The programming language Algolia Insights is a platform for analytics APIs.",
  "The programming language Algolia InstantSearch is a platform for search UI components.",
  "The programming language Algolia Places InstantSearch is a platform for places search UI components.",
  "The programming language Algolia Insights InstantSearch is a platform for analytics UI components.",
  "The programming language GraphQL is a query language for APIs.",
  "The programming language Apollo Server is a GraphQL server.",
  "The programming language Apollo Client is a GraphQL client.",
  "The programming language Relay is a GraphQL client.",
];

// Function to return a random fact
function getRandomFact() {
  const randomIndex = Math.floor(Math.random() * funFacts.length);
  return funFacts[randomIndex];
}

// Export the function for use in other files
module.exports = {
  getRandomFact,
};
